### ISSUE TITLE
build instruction

### ISSUE THREAD

**Issue by nephaste** [Aerion/uptobox-dl#1]
any build instruction to use it on Linux ...

i wonder to compile this for armv7, armv8 (aarch64) and x86_64

thanks for your help

**Comment by nephaste** [comment]
look like it did the trick

dotnet publish uptobox-dl --configuration Release --self-contained --runtime linux-x64 --output="/tmp/uptobox-dl" 

runtime are available on Microsoft dotnet website.... thanks again for this soft all is running fine on my Qnap NAS

**Comment by Aerion** [comment]
Sorry, I didn't see your issue. I'm glad to know that you made it work.
Indeed, this is a .NET core application, so to publish it on different platforms, follow the instructions specified here: 
https://docs.microsoft.com/en-us/dotnet/core/deploying/

Check out what the `self-contained` flag does: if it's set to true, the .NET framework will be embedded in the published application, and you shouldn't need any runtime installed on your target machine. But if you installed the runtime, you may set `--self-contained false`, this will reduce considerably the size of the output.

As you managed to build it, I'll close the issue, but feel free to open other issues if needed!
