### ISSUE TITLE
Download Location

### ISSUE THREAD

**Issue by PapoyBanana** [Aerion/uptobox-dl#4]
Can we make it to download the files into different folders? What syntax should I use for that?

**Comment by Aerion** [comment]
The current working directory is where the files will be downloaded.
So starting uptobox-dl from the wanted folder would do the trick.

Do you have an example, it may be clearer for me to see if something should be changed.

In my case, as I added uptobox-dl in my path, I start it where I want the files to be downloaded.

**Comment by PapoyBanana** [comment]
Yes it worked great. I did what you suggested. First, I go to the target directory. Since I put the `uptobox-dl.exe` in drive D, so I start this command `D:\uptobox-dl-v1.0.1-win-x64\uptobox-dl.exe -v -t  uptobox_token uptobox_link_1 uptobox_link_2 uptobox_link_3` from the target directory.

But I was wondering if there is a way to start uptobox-dl from directory A and make the files to be downloaded directly to directory B, C, or any other directory than where I start the uptobox-dl from.

**Comment by theRiggg** [comment]
im on ubuntu, event after I added uptobox-dl to my PATH, I still cant start it from anywhere but with the symlink I made in my Download folder It work.... I'd like to be able to use it from anywhere... someone have an idea on how to make it work ?

**Comment by theRiggg** [comment]
would be nice If we could point the folder where we want to download it.
