### ISSUE TITLE
Each Instances of download capped at 257 mbit/s.

### ISSUE THREAD

**Issue by theRiggg** [Aerion/uptobox-dl#6]
How can we remove this limitation ? I would like to be able to download at full connection speed per instances. I mean I need to open 3-4 terminals  and download files across 3-4 of them to match my speed connection.

**Comment by Aerion** [comment]
I'm pretty sure that it's related to the limitations put in place by Uptobox on the free tier, capping them at a given bandwidth.
To confirm this, could you try to download a file from Uptobox via your browser, and see at which speed it's downloading?

**Comment by theRiggg** [comment]
it's  downloading full speed. @100mb/s

**Comment by theRiggg** [comment]
across 4 terminal simultaneously I get 950-960 mbit/s with uptobox-dl, why they would cap the bandwith per instances I juste don't get it.

**Comment by theRiggg** [comment]
I just don't get it*

**Comment by theRiggg** [comment]
obviously nobody have a clue about it .....
