### ISSUE TITLE
caught exception

### ISSUE THREAD

**Issue by ArunBalaji-M** [Aerion/uptobox-dl#8]
The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing. Not sure how to fix this appreciate any help!

**Comment by Aerion** [comment]
Hi, this happens when the request made from the program to Uptobox took more than 5s.
The timeout has been increased in the latest version, 1.2.1: https://github.com/Aerion/uptobox-dl/releases/tag/v1.2.1

Feel free to reopen if the issue continues to occur.
